# Generated by Django 4.2.3 on 2023-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('appointment_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
